# Generated by Django 4.2.1 on 2025-12-07 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_class_school_user_teacher_student_parent_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Docuemnt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('file_url', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Pending', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='DocumentTeacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('document_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.docuemnt')),
                ('status_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.status')),
                ('teacher_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.teacher')),
            ],
        ),
        migrations.AddField(
            model_name='docuemnt',
            name='teachers',
            field=models.ManyToManyField(related_name='documents', through='api.DocumentTeacher', to='api.teacher'),
        ),
        migrations.AddField(
            model_name='docuemnt',
            name='uploaded_by_user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user'),
        ),
    ]
