# Generated by Django 4.2.1 on 2026-07-02 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_excuse_approval_timestamp_excuse_approved_by_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CachedAbsence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("absence_id", models.CharField(max_length=16)),
                ("data", models.JSONField()),
                ("cached_at", models.DateTimeField(auto_now=True)),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cached_absences",
                        to="api.student",
                    ),
                ),
            ],
            options={
                "unique_together": {("student", "absence_id")},
            },
        ),
    ]
