# Generated by Django 4.2.1 on 2026-07-02 22:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0003_cachedabsence"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="klasse",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="students",
                to="api.klasse",
            ),
        ),
    ]
