# Generated by Django 4.2.1 on 2026-07-02 22:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0004_alter_student_klasse"),
    ]

    operations = [
        migrations.AddField(
            model_name="excuse",
            name="parent_signed",
            field=models.BooleanField(default=False),
        ),
    ]
